config/routes.rb
Rails.application.routes.draw do
  resources :contactos do
    member do
      get :send_contact
    end
  end 
  
  resources :departamentos
	resources :proyectos
  resources :proformas
  resources :estados
  resources :asesors
  resources :cita
  root 'pages#inicio'
  get 'pages/inicio'
  get 'pages/nosotros'
  get 'pages/contactenos'
  get 'pages/proyectos'
  get 'pages/acceder'
  get 'pages/departamentos'
  get 'pages/detalledpto'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
	has_many_attached :foto_proy
	has_many :departamentos
	#mount_uploaders :foto_proy, FotoproyUploader

	validates :nombre_proy, presence: {
		message: "es requerido"
	}

	validates :ubicacion_proy, presence: {
		message: "es requerido"
	}
	validates :precio_base, presence: {
		message: "es requerido"
	}

	validates :foto_proy, presence: {
		message: "es requerido"
	}

end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  before_action :set_proyecto, only: [:show, :edit, :update, :destroy]

  # GET /proyectos
  # GET /proyectos.json
  def index
    if params[:nombre_proy]
      nombre_proy = params[:nombre_proy]
      @proyectos = Proyecto.where(["nombre_proy LIKE ?", "%#{nombre_proy}%" ])
    else
    @proyectos = Proyecto.all
  end
  end

  # GET /proyectos/1
  # GET /proyectos/1.json
  def show
    @proyecto = Proyecto.find(params[:id])
  end

  # GET /proyectos/new
  def new
    @proyecto = Proyecto.new
  end

  # GET /proyectos/1/edit
  def edit
    @proyecto =Proyecto.find(params[:id])
  end

  # POST /proyectos
  # POST /proyectos.json
  def create
    @proyecto = Proyecto.new(proyecto_params)

    respond_to do |format|
      if @proyecto.save
        format.html { redirect_to @proyecto, notice: 'Proyecto creado' }
        format.json { render :show, status: :created, location: @proyecto }
      else
        format.html { render :new }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyectos/1
  # PATCH/PUT /proyectos/1.json
  def update
    respond_to do |format|
      if @proyecto.update(proyecto_params)
        format.html { redirect_to @proyecto, notice: 'El proyecto fue actualizado.' }
        format.json { render :show, status: :ok, location: @proyecto }
      else
        format.html { render :edit }
        format.json { render json: @proyecto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyectos/1
  # DELETE /proyectos/1.json
  def destroy
    @proyecto.destroy
    respond_to do |format|
      format.html { redirect_to proyectos_url, notice: 'El proyecto fué eliminado' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyecto
      @proyecto = Proyecto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def proyecto_params
      params.require(:proyecto).permit(:nombre_proy, :descrip_proy,:ubicacion_proy, :precio_base, {foto_proy: []})
    end
end

app/helpers/proyectos_helper.rb
module ProyectosHelper
end

app/views/proyectos/_form.html.erb
<%= form_with(model: proyecto, local: true) do |form| %>
  <% if proyecto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(proyecto.errors.count, "error") %> prohibited this proyecto from being saved:</h2>

      <ul>
        <% proyecto.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>
        <div class="form-group">
          <%= form.text_field :nombre_proy, { :class => "form-control", :placeholder => "Ingrese nombre de proyecto" } %>
        </div>
        <div class="form-group">
          <%= form.text_area :descrip_proy, { :class => "form-control", :placeholder => "Descripción"  } %>
        </div>
        <div class="form-group">
          <%= form.text_area :ubicacion_proy, { :class => "form-control", :placeholder => "Ubicación"  } %>
        </div>

        <div class="form-group">
          <%= form.text_field :precio_base, { :class => "form-control", :placeholder => "Precio base"  } %>
        </div>

        <div>
          <th>Cargar imágen</th>
          <td>
            <%=form.label :Imagen %>
             <%= form.file_field :foto_proy, multiple: true, accept: 'images/*' %>
          </td>
          
        </div>

  <div class="actions">
    <%= form.submit "Guardar", :class=> "btn btn-success" %>
  </div>
<% end %>

app/views/proyectos/edit.html.erb
<h1>Editar Proyecto</h1>

<%= render 'form', proyecto: @proyecto %>

<%= link_to 'Mostrar', @proyecto %> |
<%= link_to 'Atrás', proyectos_path %>

app/views/proyectos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <p id="notice"><%= notice %></p>

      <h1>Proyectos</h1>

  <table class="table table-hover">
 
        <thead>
        <tr>
          <th>Nombre proyecto</th>
          <th>Descripción </th>
          <th>Ubicación proyecto</th>
          <th>Precio base</th>
          <th>Imagen </th>
          <td>
            <%= form_tag proyectos_path, :method => "get" do %>
            Nombre <%= text_field_tag :nombre_proy, params[:nombre_proy] %>
        
           <%= submit_tag 'Buscar', nombre_proy: nil %>
           <% end %>

          </td>
          <th colspan="3"></th>
        </tr>
        </thead>
 
        <tbody>
        <% @proyectos.each do |proyecto| %>
          <tr>
            <td><%= proyecto.nombre_proy %></td>
            <td><%= proyecto.descrip_proy %></td>
            <td><%= proyecto.ubicacion_proy %></td>
            <td><%= proyecto.precio_base %></td>
            <td><%= proyecto.foto_proy.count %></td>
            <td><%= link_to 'Mostrar', proyecto %></td>
            <td><%= link_to 'Editar', edit_proyecto_path(proyecto) %></td>
            <td><%= link_to 'Eliminar', proyecto, method: :delete, data: {confirm: 'Estás seguro?'} %></td>
            <td><%= link_to("Departamentos", departamentos_path(:proyecto_id => proyecto.id) ) %></td>
          </tr>
        <% end %>
        </tbody>
  </table>
   <nav aria-label="Page navigation example">
  <ul class="pagination">
    <li class="page-item"><a class="page-link" href="#">Anterior</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Siguiente</a></li>
  </ul>
</nav>
      <br>

      <%= link_to 'Nuevo Proyecto', new_proyecto_path, class: "btn btn-info" %>
      <%= link_to 'Volver', "pages/acceder",class: "btn btn-danger" %>

     
        
    </div>
  </div>

  <br>
      <!-- primero queremos dividirlo en 3 para saber cuantas veces se crea -->
        <% n = @proyectos.count/3 %>
        <% count = 0 %>
        <% n.downto(0) do %>
          <!-- Creamos la fila -->

          <div class="row">
              <!-- Creamos maximo 3 columnas y sale -->
                <% 3.downto(0) do |i| %>
                    <!-- Verificamos que el  count no sea mayor a la cantidad de proyectos
                    para evitar error -->
                    <% if count == @proyectos.count %>
                    <% break %>
                    <% end %>
                    <!-- Obtenemos el proyectos que toca -->
                     <% proyectos = @proyectos[count] %>
                    <!-- Utilizamos el proyectos -->
                    <div class="card">

                        <p>Insertar imagen como en clase</p>
                        <div class="col-sm-9">
                          <h5 class="card-title"><%= proyectos.nombre_proy %></h5>
                          <p class="card-text"><%= proyectos.descrip_proy %></p>
                          <a href="/pages/proyectos" class="btn btn-primary">Ir</a>
                        </div>
                    </div>
                    <!-- Aumentamos la posición para que en la siguiente utilice el siguiente proyectos -->
                    <% count += 1 %>
                <% end %>
              </div>
            <% end %>
</div>

app/views/proyectos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">

      <h1>Nuevo Proyecto</h1>

      <%= render 'form', proyecto: @proyecto %>

      <%= link_to 'Atrás', proyectos_path %>
    </div>
  </div>
</div>

app/views/proyectos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre proyecto:</strong>
  <%= @proyecto.nombre_proy %>
</p>

<p>
  <strong>Ubicacion proyecto:</strong>
  <%= @proyecto.ubicacion_proy %>
</p>


<p>
  <strong>Precio base:</strong>
  <%= @proyecto.precio_base %>
</p>

<p>
  <strong>Foto proyecto:</strong >
   <br>

<% (0...@proyecto.foto_proy.count).each do |foto_proy| %>
  <%= image_tag(@proyecto.foto_proy[foto_proy]) %> 
<% end %>
</p>

<%= link_to 'Editar', edit_proyecto_path(@proyecto) %> |
<%= link_to 'Atrás', proyectos_path %>