config/routes.rb
Rails.application.routes.draw do
  resources :contactos do
    member do
      get :send_contact
    end
  end 
  
  resources :departamentos
	resources :proyectos
  resources :proformas
  resources :estados
  resources :asesors
  resources :cita
  root 'pages#inicio'
  get 'pages/inicio'
  get 'pages/nosotros'
  get 'pages/contactenos'
  get 'pages/proyectos'
  get 'pages/acceder'
  get 'pages/departamentos'
  get 'pages/detalledpto'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/departamento.rb
class Departamento < ApplicationRecord
	has_many_attached :foto_dep
	#mount_uploaders :foto_dep, FotoproyUploader
	belongs_to :proyecto

		validates :nombre_dep, presence: {
		message: "es requerido"
	}

	validates :piso_dep, presence: {
		message: "es requerido"
	}
	validates :area, presence: {
		message: "es requerido"
	}

	validates :nro_habitacion, presence: {
		message: "es requerido"
	}

	validates :foto_dep, presence: {
		message: "es requerido"
	}

end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
       @proyecto = Proyecto.find(params[:proyecto_id])
       @departamentos = @proyecto.departamentos
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @proyecto = Proyecto.find(params[:proyecto_id])
    @departamento = Departamento.find(params[:id])
  end

  # GET /departamentos/new
  def new
    @proyecto = Proyecto.find(params[:proyecto_id])
    @departamento = Departamento.new(:proyecto_id => @proyecto.id )
  end

  # GET /departamentos/1/edit
  def edit
      @proyecto = Proyecto.find(params[:proyecto_id])
      @departamento = Departamento.find(params[:id])
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @proyecto = Proyecto.find(params[:proyecto_id])
    @departamento = Departamento.new(departamento_params)
    @departamento.proyecto = @proyecto
    respond_to do |format|
      if @departamento.save
        format.html { redirect_to departamentos_path(:proyecto_id => @proyecto.id), notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
     @proyecto = Proyecto.find(params[:proyecto_id])
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to departamento_path(@departamento, :proyecto_id => @proyecto.id), notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departamento_params
      params.require(:departamento).permit(:nombre_dep, :piso_dep, :area, :nro_habitacion, {foto_dep: []}, :proyecto_id)
    end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
          <% if @departamento.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

              <ul>
                <% @departamento.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

    <div class="form-group">
      <%= form.text_field :nombre_dep, { :class => "form-control", :placeholder => "Ingrese nombre de proyecto" } %>
    </div>

    <div class="form-group">
      <%= form.number_field :piso_dep, { :class => "form-control", :placeholder => "Número de piso" } %>
    </div>

    <div class="form-group">
      <%= form.text_area :area, { :class => "form-control", :placeholder => "Área" } %>
    </div>

    <div class="form-group">
      <%= form.number_field :nro_habitacion, { :class => "form-control", :placeholder => "Número de habitaciones" } %>
    </div>

    <div class="form-group">
      
      <%= form.object.proyecto.nombre_proy %>
    </div>

    <div>

          <th>Cargar imágen</th>
          <td>
           <%= form.file_field :foto_dep, multiple: true %>
          </td>
    </div>

  <div class="actions">
    <%= form.submit "Guardar", :class=> "btn btn-success" %>
  </div>

app/views/departamentos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">

  	<%= form_with(model: @departamento , :url => departamento_path(:proyecto_id => @proyecto.id), local: true) do |form| %>

		<%= render( :partial => "form", :locals => { :form => form }) %>

		<%= link_to 'Mostrar', @departamento %> |
		<%= link_to 'Atrás',  departamentos_path(:proyecto_id => @proyecto.id) %>

	<% end %>
    </div>
  </div>
</div>

app/views/departamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departamentos</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Proyecto</th>
      <th>Piso departamento</th>
      <th>Area departamento</th>
      <th>Nro habitacion</th>
      <th>Foto departamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nombre_dep %></td>
        <td><%= departamento.piso_dep %></td>
        <td><%= departamento.area %></td>
        <td><%= departamento.nro_habitacion %></td>
         <td><%= departamento.foto_dep.count %></td>
        <td><%= link_to 'Mostrar', departamento_path(departamento, :proyecto_id => @proyecto.id) %></td>
        <td><%= link_to 'Editar', edit_departamento_path(departamento, :proyecto_id => @proyecto.id ) %></td>
        <td><%= link_to 'Eliminar', departamento, method: :delete, data: { confirm: 'Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Departamento', new_departamento_path(:proyecto_id => @proyecto.id) %>
<%= link_to 'Atrás', proyectos_path %>

app/views/departamentos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
     	<h1>Nuevo Departamento</h1>
     	<%= form_with(model: @departamento , :url => departamentos_path(:proyecto_id => @proyecto.id), local: true) do |form| %>

	<%= render( :partial => "form", :locals => { :form => form }) %>

	<%= link_to 'Atrás',  departamentos_path(:proyecto_id => @proyecto.id) %>
<% end %>
    </div>
  </div>
</div>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre departamento:</strong>
  <%= @departamento.nombre_dep %>
</p>

<p>
  <strong>Piso:</strong>
  <%= @departamento.piso_dep %>
</p>

<p>
  <strong>Area:</strong>
  <%= @departamento.area %>
</p>

<p>
  <strong>Nro habitacion:</strong>
  <%= @departamento.nro_habitacion %>
</p>

<p>
  <strong>Foto departamento:</strong > <br>

  <% (0...@departamento.foto_dep.count).each do |foto_dep| %>
  <%= image_tag(@departamento.foto_dep[foto_dep]) %> 

<% end %>
  </p>
<%= link_to 'Editar', edit_departamento_path(@departamento) %> |
<%= link_to 'Atrás', departamentos_path(:proyecto_id => @proyecto.id) %>