config/routes.rb
Rails.application.routes.draw do
  resources :contactos do
    member do
      get :send_contact
    end
  end 
  
  resources :departamentos
	resources :proyectos
  resources :proformas
  resources :estados
  resources :asesors
  resources :cita
  root 'pages#inicio'
  get 'pages/inicio'
  get 'pages/nosotros'
  get 'pages/contactenos'
  get 'pages/proyectos'
  get 'pages/acceder'
  get 'pages/departamentos'
  get 'pages/detalledpto'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/asesor.rb
class Asesor < ApplicationRecord
end

app/controllers/asesors_controller.rb
class AsesorsController < ApplicationController
  before_action :set_asesor, only: [:show, :edit, :update, :destroy]

  # GET /asesors
  # GET /asesors.json
  def index
    @asesors = Asesor.all
  end

  # GET /asesors/1
  # GET /asesors/1.json
  def show
  end

  # GET /asesors/new
  def new
    @asesor = Asesor.new
  end

  # GET /asesors/1/edit
  def edit
  end

  # POST /asesors
  # POST /asesors.json
  def create
    @asesor = Asesor.new(asesor_params)

    respond_to do |format|
      if @asesor.save
        format.html { redirect_to @asesor, notice: 'Asesor was successfully created.' }
        format.json { render :show, status: :created, location: @asesor }
      else
        format.html { render :new }
        format.json { render json: @asesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /asesors/1
  # PATCH/PUT /asesors/1.json
  def update
    respond_to do |format|
      if @asesor.update(asesor_params)
        format.html { redirect_to @asesor, notice: 'Asesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @asesor }
      else
        format.html { render :edit }
        format.json { render json: @asesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asesors/1
  # DELETE /asesors/1.json
  def destroy
    @asesor.destroy
    respond_to do |format|
      format.html { redirect_to asesors_url, notice: 'Asesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_asesor
      @asesor = Asesor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def asesor_params
      params.require(:asesor).permit(:nombre, :apellido, :user, :password)
    end
end

app/helpers/asesors_helper.rb
module AsesorsHelper
end

app/views/asesors/_form.html.erb
<%= form_with(model: asesor, local: true) do |form| %>
  <% if asesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(asesor.errors.count, "error") %> prohibited this asesor from being saved:</h2>

      <ul>
        <% asesor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, {:class => "form-control", :placeholder => "Ingrese nombre", :requerid =>
      "requerid"} %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
<%= form.text_field :apellido, {:class => "form-control", :placeholder => "Ingrese apellido", :requerid =>
      "requerid"} %> 
  </div>

  <div class="field">
    <%= form.label :Usuario %>   
    <%= form.text_field :user, {:class => "form-control", :placeholder => "Ingrese Usuario", :requerid =>
      "requerid"} %> 
  </div>

  <div class="field">
    <%= form.label :password %>
      <%= form.text_field :password, {:class => "form-control", :placeholder => "Ingrese Contraseña", :requerid =>
      "requerid"} %> 
  </div>

  <div class="actions">
    <%= form.submit(class:"btn btn-success")%>
  </div>
<% end %>

app/views/asesors/edit.html.erb
<h1>Editing Asesor</h1>

<%= render 'form', asesor: @asesor %>

<%= link_to 'Show', @asesor %> |
<%= link_to 'Back', asesors_path %>

app/views/asesors/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <p id="notice"><%= notice %></p>
      <h1>Asesores</h1>
      <table class="table table-hover table-striped table-bordered">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>Usuario</th>
          <th>Contraseña</th>
          <th colspan="3">Opciones</th>
        </tr>
        </thead>

        <tbody>
        <% @asesors.each do |asesor| %>
          <tr>
            <td><%= asesor.nombre %></td>
            <td><%= asesor.apellido %></td>
            <td><%= asesor.user %></td>
            <td><%= asesor.password %></td>
            <td><%= link_to 'Mostrar', asesor %></td>
            <td><%= link_to 'Editar', edit_asesor_path(asesor) %></td>
            <td><%= link_to 'Eliminar', asesor, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'Nuevo Asesor', new_asesor_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/asesors/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-9">
      <h1>Nuevo Asesor</h1>

      <%= render 'form', asesor: @asesor %>

      <%= link_to 'Back', asesors_path %>
    </div>
  </div>
</div>

app/views/asesors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @asesor.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @asesor.apellido %>
</p>

<p>
  <strong>User:</strong>
  <%= @asesor.user %>
</p>

<p>
  <strong>Password:</strong>
  <%= @asesor.password %>
</p>

<%= link_to 'Edit', edit_asesor_path(@asesor) %> |
<%= link_to 'Back', asesors_path %>