config/routes.rb
Rails.application.routes.draw do
  resources :contactos do
    member do
      get :send_contact
    end
  end 
  
  resources :departamentos
	resources :proyectos
  resources :proformas
  resources :estados
  resources :asesors
  resources :cita
  root 'pages#inicio'
  get 'pages/inicio'
  get 'pages/nosotros'
  get 'pages/contactenos'
  get 'pages/proyectos'
  get 'pages/acceder'
  get 'pages/departamentos'
  get 'pages/detalledpto'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/estado.rb
class Estado < ApplicationRecord
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  before_action :set_estado, only: [:show, :edit, :update, :destroy]

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
  end

  # GET /estados/new
  def new
    @estado = Estado.new
  end

  # GET /estados/1/edit
  def edit
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(estado_params)

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render :show, status: :created, location: @estado }
      else
        format.html { render :new }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estados/1
  # PATCH/PUT /estados/1.json
  def update
    respond_to do |format|
      if @estado.update(estado_params)
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { render :show, status: :ok, location: @estado }
      else
        format.html { render :edit }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado.destroy
    respond_to do |format|
      format.html { redirect_to estados_url, notice: 'Estado was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estado
      @estado = Estado.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estado_params
      params.require(:estado).permit(:icodigo, :descripcion)
    end
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/views/estados/_form.html.erb
<%= form_with(model: estado, local: true) do |form| %>
  <% if estado.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estado.errors.count, "error") %> prohibited this estado from being saved:</h2>

      <ul>
        <% estado.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Id %>   
      <%= form.number_field :icodigo, {:class => "form-control", :placeholder => "Ingrese id", :requerid =>
      "requerid"} %> 
  </div>

  <div class="field">
    <%= form.label :Descripción %>
    <%= form.text_field :descripcion, {:class => "form-control", :placeholder => "Ingrese descripcion", :requerid =>
      "requerid"} %> 
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<h1>Editar Estado</h1>

<%= render 'form', estado: @estado %>

<%= link_to 'Mostrar', @estado %> |
<%= link_to 'Regresar', estados_path %>

app/views/estados/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <p id="notice"><%= notice %></p>

      <h1>Estados</h1>


      <table class="table table-hover table-striped table-bordered">
        <thead>
        <tr>
          <th>Id</th>
          <th>Descripción</th>
          <th colspan="3">Opciones</th>
        </tr>
        </thead>

        <tbody>
        <% @estados.each do |estado| %>
          <tr>
            <td><%= estado.icodigo %></td>
            <td><%= estado.descripcion %></td>
            <td><%= link_to 'Mostrar', estado %></td>
            <td><%= link_to 'Editar', edit_estado_path(estado) %></td>
            <td><%= link_to 'Eliminar', estado, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'Nuevo Estado', new_estado_path, class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/estados/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
<h1>Nuevo Estado</h1>

<%= render 'form', estado: @estado %>





<%= link_to 'Regresar', estados_path %>
    </div>
  </div>
</div>

app/views/estados/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <p id="notice"><%= notice %></p>

      <p>
        <strong>Id:</strong>
        <%= @estado.icodigo %>
      </p>

      <p>
        <strong>Descripción:</strong>
        <%= @estado.descripcion %>
      </p>

      <%= link_to 'Editar', edit_estado_path(@estado) %> |
      <%= link_to 'Regresar', estados_path %>
    </div>
  </div>
</div>